---
apiVersion: v1
kind: Service
metadata:
  name: my-ext-hello-service
  labels:
    app: my-ext-hello-service
spec:
  ports:
    - port: 8081
      name: http
      targetPort: 8081
  selector:
    app: my-ext-hello-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ext-hello-service
  labels:
    app: my-ext-hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ext-hello-service
  template:
    metadata:
      labels:
        app: my-ext-hello-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/my-ext-hello/my-ext-hello-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: my-ext-hello
spec:
  to:
    kind: Service
    name: my-ext-hello-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
